### PR TITLE
Fix bugs and Add free cam

### PR DESCRIPTION
**Pull request by Lyght-1**
- Fixed the bug where the speed would be resetted to 5 after some cutscene/warp

- Fixed the collision toggle

- Fixed the value not being correctly resetted when going back to the pause menu

- Added a Free Cam
Input for it :
Ctrl - Toggle free cam / reset the cam
Shift - Move the cam faster

W - Forward
A -  Left
S - Back
D - Right
Q - Up
E - Down

i - Rotate Down
J - Rotate Left
K - Rotate Up
L - Rotate Right

### CODE REVIEW

**Review by aldelaro5 — CHANGES_REQUESTED** [review]
Ok I will have to ask if it's possible for you to split the PR because I can't reasonably have a pr containing one feature and 3 bugfixes at once. It's also better on your end because it will allow me to get the bugfixes merged MUCH QUICKER than the free cam since these are more easily assesable.

That being said, I understand you may not have foresaw this so if you can't, I could proceed, but I am warning you that this might causes delays especially with the free cam as I do not like using the keyboard to rotate when in every free came I know of, you usually use the mouse for this (like hold right click, move, something like that). Addressing these would take much longer than for me to check the 3 other bugfixes so this is why it's beneficial for both you and me to split this into ideally 4 prs. Additionally, I seem to see some weird styling changes that doesn't seem to belong which might be removed, but I need to get an answer on splitting before deeply reviewing this.

As for free cam, in the event that you don't want to use the mouse, what I could do is author my code on top of your branch (when I get the time of course) which will essentially look like the commit had multiple authors (it's a thing you can do). Your choice here.

**Comment by Lyght-1** [comment]
Alright ill try to split it into different pr tomorrow.

As for using mouse in the free cam, it seems the game disabled the mouse in the project settings, but i didnt look that much into it. It wouldnt be oppose to using the mouse for it tho

**Comment by aldelaro5** [comment]
ok when you do, I will be closing this one :)

**Comment by aldelaro5** [comment]
Closing as all the bugfixes got merged and for free cam, see #6

**Pull request closed without merging**
